todd@ubuntu:~/automation/napalm_stuff$ python3 config_script_ios.py 
Connected to:  r1
Connected to:  r3
Connected to:  r2
Connected to:  r4
Connected to:  r5
('config term\n'
 'Enter configuration commands, one per line.  End with CNTL/Z.\n'
 'R1(config)#ip access-list extended test\n'
 'R1(config-ext-nacl)#  permit ip any any\n'
 'R1(config-ext-nacl)#\n'
 'R1(config-ext-nacl)#int loopback 2\n'
 'R1(config-if)# ip access-group test in\n'
 'R1(config-if)# ip access-group test out\n'
 'R1(config-if)#end\n'
 'R1#')
('config term\n'
 'Enter configuration commands, one per line.  End with CNTL/Z.\n'
 'R3(config)#ip access-list extended test\n'
 'R3(config-ext-nacl)#  permit ip any any\n'
 'R3(config-ext-nacl)#\n'
 'R3(config-ext-nacl)#int loopback 2\n'
 'R3(config-if)# ip access-group test in\n'
 'R3(config-if)# ip access-group test out\n'
 'R3(config-if)#end\n'
 'R3#')
('config term\n'
 'Enter configuration commands, one per line.  End with CNTL/Z.\n'
 'R2(config)#ip access-list extended test\n'
 'R2(config-ext-nacl)#  permit ip any any\n'
 'R2(config-ext-nacl)#\n'
 'R2(config-ext-nacl)#int loopback 2\n'
 'R2(config-if)# ip access-group test in\n'
 'R2(config-if)# ip access-group test out\n'
 'R2(config-if)#end\n'
 'R2#')
('config term\n'
 'Enter configuration commands, one per line.  End with CNTL/Z.\n'
 'R4(config)#ip access-list extended test\n'
 'R4(config-ext-nacl)#  permit ip any any\n'
 'R4(config-ext-nacl)#\n'
 'R4(config-ext-nacl)#int loopback 2\n'
 'R4(config-if)# ip access-group test in\n'
 'R4(config-if)# ip access-group test out\n'
 'R4(config-if)#end\n'
 'R4#')
('config term\n'
 'Enter configuration commands, one per line.  End with CNTL/Z.\n'
 'R5(config)#ip access-list extended test\n'
 'R5(config-ext-nacl)#  permit ip any any\n'
 'R5(config-ext-nacl)#\n'
 'R5(config-ext-nacl)#int loopback 2\n'
 'R5(config-if)# ip access-group test in\n'
 'R5(config-if)# ip access-group test out\n'
 'R5(config-if)#end\n'
 'R5#')
('config term\n'
 'Enter configuration commands, one per line.  End with CNTL/Z.\n'
 'R1(config)#\n'
 'R1(config)#ntp server 8.8.8.8\n'
 'R1(config)#\n'
 'R1(config)#username test123 password testabc\n'
 'R1(config)#\n'
 'R1(config)#logging buffered\n'
 'R1(config)#\n'
 'R1(config)#\n'
 'R1(config)#end\n'
 'R1#')
('config term\n'
 'Enter configuration commands, one per line.  End with CNTL/Z.\n'
 'R3(config)#\n'
 'R3(config)#ntp server 8.8.8.8\n'
 'R3(config)#\n'
 'R3(config)#username test123 password testabc\n'
 'R3(config)#\n'
 'R3(config)#logging buffered\n'
 'R3(config)#\n'
 'R3(config)#\n'
 'R3(config)#end\n'
 'R3#')
('config term\n'
 'Enter configuration commands, one per line.  End with CNTL/Z.\n'
 'R2(config)#\n'
 'R2(config)#ntp server 8.8.8.8\n'
 'R2(config)#\n'
 'R2(config)#username test123 password testabc\n'
 'R2(config)#\n'
 'R2(config)#logging buffered\n'
 'R2(config)#\n'
 'R2(config)#\n'
 'R2(config)#end\n'
 'R2#')
('config term\n'
 'Enter configuration commands, one per line.  End with CNTL/Z.\n'
 'R4(config)#\n'
 'R4(config)#ntp server 8.8.8.8\n'
 'R4(config)#\n'
 'R4(config)#username test123 password testabc\n'
 'R4(config)#\n'
 'R4(config)#logging buffered\n'
 'R4(config)#\n'
 'R4(config)#\n'
 'R4(config)#end\n'
 'R4#')
('config term\n'
 'Enter configuration commands, one per line.  End with CNTL/Z.\n'
 'R5(config)#\n'
 'R5(config)#ntp server 8.8.8.8\n'
 'R5(config)#\n'
 'R5(config)#username test123 password testabc\n'
 'R5(config)#\n'
 'R5(config)#logging buffered\n'
 'R5(config)#\n'
 'R5(config)#\n'
 'R5(config)#end\n'
 'R5#')
[None, None, None, None, None]
todd@ubuntu:~/automation/napalm_stuff$ 
